flowchart LR
  MAIN --> RDSUT28
  MAIN-EX --> PITIBAN2
  MAIN-EX --> RDSUT10
  MAIN-EX --> RDSUT10
  B20-PERSTART --> PNBTBLC2
  B20-PERSTART --> RDSUT10
  B20-EX --> RDSCONT
  C00-CENTRALI --> RDSUT27
  C00-EX --> RDSUT10
  E00-ELABORA --> RDSUT10
  E00-ELABORA --> RDSUT10
  E00-EX --> RDSUT10
  E15-INIZIALIZZO --> RDSUT10
  E15-INIZIALIZZO --> PDSNA42
  E15-INIZIALIZZO --> PDSNA02
  E15-INIZIALIZZO --> PDSAU41
  E15-INIZIALIZZO --> RDSNA12
  E20-ELABORA20 --> RDSPD13
  E20-ELABORA20 --> RDSUT14
  E20-EX --> RDSUT28
  E22-ELABORA22 --> PNBTCFIB
  E22-ELABORA22 --> PDSPD07
  E22-EX --> PDSPD05
  E221-ELABORA221 --> PDSPD08
  E221-ELABORA221 --> PDSPD16
  E221-EX --> PDSLOCK
  L10-LETTURA --> PDSPD13
  L10-LETTURA --> PDSPD16
  L10-EX --> RDSUT28
  L11-DATICOMUNI --> PDSNA42
  L11-DATICOMUNI --> PDSNA02
  L11-DATICOMUNI --> PDSAU41
  L11-DATICOMUNI --> RDSNA12
  L11-EX --> RDSNA13
  L11-EX --> PDSPD16
  L11-X-DTCODO-EX --> PDSLOCK
  L11S-EX --> RDSUT28
  L13-PAGAMENTI --> PDSNA42
  L13-PAGAMENTI --> PDSNA02
  L13-PAGAMENTI --> PDSAU41
  L13-PAGAMENTI --> RDSNA12
  L13-EX --> RDSPD13
  L14-CHK-PAGAMENTI --> RDSUT14
  L14-CHK-PAGAMENTI --> RDSUT28
  L14-EX --> PNBTCFIB
  L141-PMEDTRICA-1 --> PDSPD07
  L141-EX --> PDSPD05
  L16-RECUPERI --> PDSPD08
  L16-RECUPERI --> PDSPD16
  L16-EX --> PDSLOCK
  L17-CHKFLD-RECUPERI --> PDSPD13
  L17-CHKFLD-RECUPERI --> PDSPD16
  L17-EX --> RDSUT28
  L18-SOMMA-RECUPERI --> PDSNA42
  L18-SOMMA-RECUPERI --> PDSNA02
  L18-SOMMA-RECUPERI --> PDSAU41
  L18-SOMMA-RECUPERI --> RDSNA12
  L18-EX --> RDSNA13
  L19-SITUAZIODO --> PDSPD16
  L19-SITUAZIODO --> PDSLOCK
  L19-EX --> RDSUT28
  L22-ANAGRAFICI --> PDSNA42
  L22-ANAGRAFICI --> PDSNA02
  L22-ANAGRAFICI --> PDSAU41
  L22-ANAGRAFICI --> RDSNA12
  L22-EX --> RDSNA13
  L25-DELEGHE --> PDSPD16
  L25-DELEGHE --> PDSLOCK
  L25-EX --> RDSUT28
  L26-CHKFLD-DELEGHE --> PDSNA42
  L26-CHKFLD-DELEGHE --> PDSNA02
  L26-CHKFLD-DELEGHE --> PDSAU41
  L26-CHKFLD-DELEGHE --> RDSNA12
  L26-EX --> RDSNA13
  L27-CARICA-DELEGHE --> PDSPD16
  L27-CARICA-DELEGHE --> PDSLOCK
  L27-EX --> RDSUT28
  L28-DATIANF --> PDSNA42
  L28-DATIANF --> PDSNA02
  L28-DATIANF --> PDSAU41
  L28-DATIANF --> RDSNA12
  L28-EX --> RDSNA13
  L29-CHKFLD-DATIANF --> PDSPD16
  L29-CHKFLD-DATIANF --> PDSLOCK
  L29-EX --> RDSUT28
  L30-CARICOANF --> PDSNA42
  L30-CARICOANF --> PDSNA02
  L30-CARICOANF --> PDSAU41
  L30-CARICOANF --> RDSNA12
  L30-EX --> RDSNA13
  L281-ANFDIRETTI --> PDSPD16
  L281-ANFDIRETTI --> PDSLOCK
  L281-EX --> RDSUT28
  L291-CHK-ANFDIR --> PDSNA42
  L291-CHK-ANFDIR --> PDSNA02
  L291-CHK-ANFDIR --> PDSAU41
  L291-CHK-ANFDIR --> RDSNA12
  L291-EX --> RDSNA13
  L301-FLD-ANFDIR --> PDSPD16
  L301-FLD-ANFDIR --> PDSLOCK
  L301-EX --> RDSUT28
  L31-DSCOMUNI --> PDSNA42
  L31-DSCOMUNI --> PDSNA02
  L31-DSCOMUNI --> PDSAU41
  L31-DSCOMUNI --> RDSNA12
  L31-EX --> RDSNA13
  L33-NASPI --> PDSPD16
  L33-NASPI --> PDSLOCK
  L33-EX --> RDSUT28
  L331-RICALCOLO --> PDSNA42
  L331-RICALCOLO --> PDSNA02
  L331-RICALCOLO --> PDSAU41
  L331-RICALCOLO --> RDSNA12
  L331-EX --> RDSNA13
  L34-DISCOLL --> PDSPD16
  L34-DISCOLL --> PDSLOCK
  L34-EX --> RDSUT28
  L35-AUTASPI --> PDSNA42
  L35-AUTASPI --> PDSNA02
  L35-AUTASPI --> PDSAU41
  L35-AUTASPI --> RDSNA12
  L35-EX --> RDSNA13
  L35B-EX --> PDSPD16
  L35B-EX --> PDSLOCK
  L351-CHKFLD-AUTASPI --> RDSUT28
  L352-CARICOAUT --> PDSNA42
  L352-CARICOAUT --> PDSNA02
  L352-CARICOAUT --> PDSAU41
  L352-CARICOAUT --> RDSNA12
  L352-EX --> RDSNA13
  L353-EX --> PDSPD16
  L353-EX --> PDSLOCK
  L3541-EX --> RDSUT28
  L3542-EX --> PDSNA42
  L3542-EX --> PDSNA02
  L3542-EX --> PDSAU41
  L3542-EX --> RDSNA12
  L3561-EX --> RDSNA13
  L3562-EX --> PDSPD16
  L3562-EX --> PDSLOCK
  L3581-EX --> RDSUT28
  L3582-EX --> PDSNA42
  L3582-EX --> PDSNA02
  L3582-EX --> PDSAU41
  L3582-EX --> RDSNA12
  L36-ORDSANMARINO --> RDSNA13
  L36-EX --> PDSPD16
  L36-EX --> PDSLOCK
  L37-RIMPATRIATI --> RDSUT28
  L38-ASPRI --> PDSNA42
  L38-ASPRI --> PDSNA02
  L38-ASPRI --> PDSAU41
  L38-ASPRI --> RDSNA12
  L38-EX --> RDSNA13
  L37-EX --> PDSPD16
  L37-EX --> PDSLOCK
  L41-ANTNASPI --> RDSUT28
  L42-DECANTNASPI --> PDSNA42
  L42-DECANTNASPI --> PDSNA02
  L42-DECANTNASPI --> PDSAU41
  L42-DECANTNASPI --> RDSNA12
  L42-EX --> RDSNA13
  L40-REGIMECEE --> PDSPD16
  L40-REGIMECEE --> PDSLOCK
  L43-EDILI --> RDSUT28
  L43-EX --> PDSNA42
  L43-EX --> PDSNA02
  L43-EX --> PDSAU41
  L43-EX --> RDSNA12
  L46-MARITTIMI --> RDSNA13
  L46-EX --> PDSPD16
  L46-EX --> PDSLOCK
  L49-SOSPENSIONI --> RDSUT28
  L49-EX --> PDSNA42
  L49-EX --> PDSNA02
  L49-EX --> PDSAU41
  L49-EX --> RDSNA12
  L50-CHKFLD-SOSPE --> RDSNA13
  L50-EX --> PDSPD16
  L50-EX --> PDSLOCK
  L51-CARICOSOS --> RDSUT28
  L51-EX --> PDSNA42
  L51-EX --> PDSNA02
  L51-EX --> PDSAU41
  L51-EX --> RDSNA12
  L52-TEOEROGABI --> RDSNA13
  L52-EX --> PDSPD16
  L52-EX --> PDSLOCK
  L53-CHKFLD-TEOEROGABI --> RDSUT28
  L53-EX --> PDSNA42
  L53-EX --> PDSNA02
  L53-EX --> PDSAU41
  L53-EX --> RDSNA12
  L54-CARICOPET --> RDSNA13
  L54-EX --> PDSPD16
  L54-EX --> PDSLOCK
  L55-PENSIONI --> RDSUT28
  L55-EX --> PDSNA42
  L55-EX --> PDSNA02
  L55-EX --> PDSAU41
  L55-EX --> RDSNA12
  L56-CHKFLD-PENSIONI --> RDSNA13
  L56-EX --> PDSPD16
  L56-EX --> PDSLOCK
  L57-CARICOPEN --> RDSUT28
  L57-EX --> PDSNA42
  L57-EX --> PDSNA02
  L57-EX --> PDSAU41
  L57-EX --> RDSNA12
  L59-EX --> RDSNA13
  L68-EX --> PDSPD16
  L68-EX --> PDSLOCK
  L69-EX --> RDSUT28
  E24-CALCOLO --> PDSNA42
  E24-CALCOLO --> PDSNA02
  E24-CALCOLO --> PDSAU41
  E24-CALCOLO --> RDSNA12
  E24-EX --> RDSNA13
  E25-CONTROLLI --> PDSPD16
  E25-CONTROLLI --> PDSLOCK
  E26-PAGABILI --> RDSUT28
  E26-EX --> PDSNA42
  E26-EX --> PDSNA02
  E26-EX --> PDSAU41
  E26-EX --> RDSNA12
  E27-DEFINITE --> RDSNA13
  E27-EX --> PDSPD16
  E27-EX --> PDSLOCK
  E28-UPD-IMPO --> RDSUT28
  E28-EX --> PDSNA42
  E28-EX --> PDSNA02
  E28-EX --> PDSAU41
  E28-EX --> RDSNA12
  E30-AGGIORNA --> RDSNA13
  E30-EX --> PDSPD16
  E30-EX --> PDSLOCK
  E31-ANAGRAFICA --> RDSUT28
  E31-EX --> PDSNA42
  E31-EX --> PDSNA02
  E31-EX --> PDSAU41
  E31-EX --> RDSNA12
  E311-EX --> RDSNA13
  E312-TITOLARITA --> PDSPD16
  E312-TITOLARITA --> PDSLOCK
  E312-EX --> RDSUT28
  E33-DATI-APPOGGIO --> PDSNA42
  E33-DATI-APPOGGIO --> PDSNA02
  E33-DATI-APPOGGIO --> PDSAU41
  E33-DATI-APPOGGIO --> RDSNA12
  E33-EX --> RDSNA13
  E331-BLKPA-EX --> PDSPD16
  E331-BLKPA-EX --> PDSLOCK
  E35-UPD-FILE --> RDSUT28
  E35-EX --> PDSNA42
  E35-EX --> PDSNA02
  E35-EX --> PDSAU41
  E35-EX --> RDSNA12
  E392-UPD-DATICOMUNI-A --> RDSNA13
  E392-EX --> PDSPD16
  E392-EX --> PDSLOCK
  E40-UPD-DATICOMUNI --> RDSUT28
  E40-EX --> PDSNA42
  E40-EX --> PDSNA02
  E40-EX --> PDSAU41
  E40-EX --> RDSNA12
  E43-UPD-RECUPERI --> RDSNA13
  E43-EX --> PDSPD16
  E43-EX --> PDSLOCK
  E44-UPD-IMPORTI --> RDSUT28
  E44-EX --> PDSNA42
  E44-EX --> PDSNA02
  E44-EX --> PDSAU41
  E44-EX --> RDSNA12
  E441-WRT-STOREC --> RDSNA13
  E441-EX --> PDSPD16
  E441-EX --> PDSLOCK
  E45-DLT-EFFEROGATI --> RDSUT28
  E45-EX --> PDSNA42
  E45-EX --> PDSNA02
  E45-EX --> PDSAU41
  E45-EX --> RDSNA12
  E46-WRT-EFFEROGATI --> RDSNA13
  E46-EX --> PDSPD16
  E46-EX --> PDSLOCK
  E47-UPD-SITUAZIODO --> RDSUT28
  E47-EX --> PDSNA42
  E47-EX --> PDSNA02
  E47-EX --> PDSAU41
  E47-EX --> RDSNA12
  E50-PREPARO-PAGAMENTI --> RDSNA13
  E50-EX --> PDSPD16
  E50-EX --> PDSLOCK
  E51-UPD-PAGAMENTI --> RDSUT28
  E51-EX --> PDSNA42
  E51-EX --> PDSNA02
  E51-EX --> PDSAU41
  E51-EX --> RDSNA12
  E52-WRT-PAGAMENTI --> RDSNA13
  E52-EX --> PDSPD16
  E52-EX --> PDSLOCK
  E53-UPD-ANFDIR --> RDSUT28
  E53-EX --> PDSNA42
  E53-EX --> PDSNA02
  E53-EX --> PDSAU41
  E53-EX --> RDSNA12
  E55-UPD-AUTLASPI --> RDSNA13
  E55-EX --> PDSPD16
  E55-EX --> PDSLOCK
  E56-EX --> RDSUT28
  E65-WRT-STOANF --> PDSNA42
  E65-WRT-STOANF --> PDSNA02
  E65-WRT-STOANF --> PDSAU41
  E65-WRT-STOANF --> RDSNA12
  E65-EX --> RDSNA13
  E66-WRT-STOSOS --> PDSPD16
  E66-WRT-STOSOS --> PDSLOCK
  E67-WRT-STOAUTLA --> RDSUT28
  E67-EX --> PDSNA42
  E67-EX --> PDSNA02
  E67-EX --> PDSAU41
  E67-EX --> RDSNA12
  E60-SINCRONIZZO --> RDSNA13
  E60-EX --> PDSPD16
  E60-EX --> PDSLOCK
  E62-SCRIVO --> RDSUT28
  E62-EX --> PDSNA42
  E62-EX --> PDSNA02
  E62-EX --> PDSAU41
  E62-EX --> RDSNA12
  E64-RISCRIVO --> RDSNA13
  E64-EX --> PDSPD16
  E64-EX --> PDSLOCK
  F00-FINALI --> RDSUT28
  F00-FINALI --> PDSNA42
  F00-FINALI --> PDSNA02
  F00-FINALI --> PDSAU41
  F00-FINALI --> RDSNA12
  F00-FINALI --> RDSNA13
  F00-FINALI --> PDSPD16
  F00-FINALI --> PDSLOCK
