flowchart TD
  E20-ELABORA20 --> RDSUT28
  L11-DATICOMUNI --> PITIBAN2
  L11-DATICOMUNI --> RDSUT10
  L11-DATICOMUNI --> RDSUT10
  L13-PAGAMENTI --> PNBTBLC2
  L13-PAGAMENTI --> RDSUT10
  L14-CHK-PAGAMENTI --> RDSCONT
  L16-RECUPERI --> RDSUT27
  L33-NASPI --> RDSUT10
  L33-NASPI --> RDSUT10
  L33-NASPI --> RDSUT10
  L54-CARICOPET --> RDSUT10
  L54-CARICOPET --> RDSUT10
  L68-EX --> PDSNA42
  L68-EX --> PDSNA02
  L68-EX --> PDSAU41
  L68-EX --> RDSNA12
  E24-CALCOLO --> RDSPD13
  E30-AGGIORNA --> RDSUT14
  E30-AGGIORNA --> RDSUT28
  E31-ANAGRAFICA --> PNBTCFIB
  E33-DATI-APPOGGIO --> PDSPD07
  E35-UPD-FILE --> PDSPD05
  E35-UPD-FILE --> PDSPD08
  E44-UPD-IMPORTI --> PDSPD16
  E44-UPD-IMPORTI --> PDSLOCK
  E45-DLT-EFFEROGATI --> PDSPD13
  E45-DLT-EFFEROGATI --> PDSPD16
  F00-FINALI --> RDSUT28
  F00-FINALI --> PDSNA42
  F00-FINALI --> PDSNA02
  F00-FINALI --> PDSAU41
  F00-FINALI --> RDSNA12
  F00-FINALI --> RDSNA13
  F00-FINALI --> PDSPD16
  F00-FINALI --> PDSLOCK
  %% ... (continues for all 200 calls in the batch)
